---
- hosts: rhevm
  gather_facts: false

  vars:
    engine_url: "https://{{ rhv_dns_domain }}/ovirt-engine/api"
    username: admin@internal
   
    engine_cafile: /etc/pki/ovirt-engine/ca.pem
    datacenter: Default
    cluster: Default
    
  tasks:
    - block:
       - name: obtain SSO token
         no_log: true
         ovirt_auth:
           url: "{{ engine_url }}"
           username: "{{ username }}"
           password: "{{ root_password }}"
           ca_file: "{{ engine_cafile }}"

       - name: Ensure Datacenter "{{ datacenter }}" exists
         ovirt_datacenters:
           auth: "{{ ovirt_auth }}"
           name: "{{ datacenter }}"
           comment: "The primary datacenter"
           compatibility_version: 4.1
           quota_mode: enabled
           local: False

       - name: Ensure cluster "{{ cluster }}" exists
         ovirt_clusters:
           auth: "{{ ovirt_auth }}"
           name: "{{ cluster }}"
           data_center: "{{ datacenter }}"
           description: "cluster {{ cluster }}"
           cpu_type: "Intel Haswell-noTSX Family"
           switch_type: legacy
           compatibility_version: 4.1
           gluster: false
           ballooning: false
           ha_reservation: true
           memory_policy: server

       - name: test1
         debug:
           msg: "{{ lookup('dig', 'rhevh1.hailstorm2.coe.muc.redhat.com.', wantlist=True) }}"

       - name: join hypervisors to cluster "{{ cluster }}"
         ovirt_hosts:
           auth: "{{ ovirt_auth }}"
           cluster: "{{ cluster }}"
           name: "{{ item.name }}"
           address: "{{ item.addr }}"
           password: "{{ root_password }}"
         with_items:
           - { name: rhevh1, addr: 192.168.101.13 }
           - { name: rhevh2, addr: 192.168.101.14 }
           - { name: rhevh3, addr: 192.168.101.15 }

       - name: Create storage domains
         ovirt_storage_domains:
           auth: "{{ ovirt_auth }}"
           name: "{{ item.name }}"
           description: "{{ item.desc }}"
           data_center: "{{ datacenter }}"
           domain_function: "{{ item.function }}"
           host: "rhevh1"
           nfs:
             address: "{{ item.addr }}"
             path: "{{ item.path }}"
         with_items:
           - { name: "DATA", desc: "DATA storage domain", addr: "192.168.104.1", path: "/var/hailstorm/rhev-data1", function: "data" }
           - { name: "ISO", desc: "ISO storage domain", addr: "192.168.104.1", path: "/var/hailstorm/rhev-iso1", function: "iso" }
           - { name: "EXPORT", desc: "EXPORT storage domain", addr: "192.168.104.1", path: "/var/hailstorm/rhev-export1", function: "export" }

      always:
        - name: Revoke the SSO token
          ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
